#!/usr/bin/env python3
"""Regression tests for tools/migrate_workspace.py (the workspace migrator).

The migrator carries a LADDER of hops — v2.5 -> v2.6 -> v2.7 — and walks it
from whatever the workspace is pinned at up to the newest version, in one run.
Both hops are supported public capability; the v2.5 one is not a leftover.

The migrator's contract, pinned here:
  - it rewrites the PROTOCOL_VERSION row STRUCTURALLY (any inner spacing) and
    flips a `[PROTOCOL vX.Y]` stamp ONLY on a stamp-bearing line (a heading or a
    tool docstring banner) — so the same literal token inside a PROXY_AUTH row
    or a memory body is left byte-for-byte untouched;
  - it preserves each file's line endings exactly (no CRLF<->LF rewrite);
  - it is idempotent (already-newest is a no-op) and refuses an unsupported
    pin, naming the pins that ARE supported;
  - --dry-run writes nothing;
  - it NEVER edits the PROXY_AUTH slot (authority is first-hand only) but PRINTS
    the reword when the slot predates the canonical wording;
  - it PRINTS advice for the new v2.7 slots without stamping them, flagged by
    whether each applies to this workspace's profile.

Several fixtures are HAND-BUILT (explicit file content), not generated by
downgrading a fresh stamp, so the adversarial cases are pinned independently of
the migrator's own token strategy.

Stdlib unittest only, importlib-loading the tools like test_git_sync_stamp.py:

    python -m unittest discover -s tests
"""
import importlib.util
import io
import re
import sys
import tempfile
import unittest
from contextlib import redirect_stdout, redirect_stderr
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _load(mod_name, rel_path):
    spec = importlib.util.spec_from_file_location(mod_name, ROOT / rel_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


np = _load("new_project", "tools/new_project.py")
cc = _load("conformance_check", "tools/conformance_check.py")
mw = _load("migrate_workspace", "tools/migrate_workspace.py")


def _stamp(dest, extra_args):
    """Stamp a fresh v2.7 workspace at `dest`; return exit code."""
    saved = sys.argv
    out, err = io.StringIO(), io.StringIO()
    try:
        sys.argv = ["new_project.py", "--name", "t", "--dest", str(dest)] + extra_args
        with redirect_stdout(out), redirect_stderr(err):
            return np.main()
    finally:
        sys.argv = saved


def _downgrade(ws, to="v2.6"):
    """Turn a fresh v2.7 stamp into a `to`-version workspace — the inverse of
    the migrator's flip, for the happy-path round-trip only. (The edge cases
    below use hand-built fixtures instead, so they don't depend on this.)

    `to="v2.5"` produces the OLDEST supported pin, which is what exercises the
    chained two-hop path."""
    for p in mw._text_files(ws):
        text = p.read_text(encoding="utf-8")
        new = text.replace("[PROTOCOL v2.7]", f"[PROTOCOL {to}]")
        if p.name == "BINDINGS.md":
            new = new.replace("| PROTOCOL_VERSION | v2.7 |",
                              f"| PROTOCOL_VERSION | {to} |")
        if new != text:
            p.write_text(new, encoding="utf-8")


def _set_slot(ws, slot, value):
    """Overwrite a single `| SLOT | ... |` row in BINDINGS.md."""
    b = ws / "BINDINGS.md"
    lines = b.read_text(encoding="utf-8").splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.lstrip().startswith(f"| {slot} |"):
            eol = "\n" if line.endswith("\n") else ""
            lines[i] = f"| {slot} | {value} |{eol}"
            break
    b.write_text("".join(lines), encoding="utf-8")


def _pver_row(ws):
    """The current PROTOCOL_VERSION row line in BINDINGS.md (no terminator),
    matched spacing-tolerantly."""
    for line in (ws / "BINDINGS.md").read_text(encoding="utf-8").splitlines():
        cells = [c.strip() for c in line.split("|")]
        if len(cells) >= 4 and cells[1] == "PROTOCOL_VERSION":
            return line
    return None


def _migrate_main(ws, extra=None):
    """Run migrate_workspace.main() against `ws`; return (code, stdout+stderr)."""
    saved = sys.argv
    out, err = io.StringIO(), io.StringIO()
    try:
        sys.argv = ["migrate_workspace.py", "--workspace", str(ws)] + (extra or [])
        with redirect_stdout(out), redirect_stderr(err):
            code = mw.main()
    finally:
        sys.argv = saved
    return code, out.getvalue() + err.getvalue()


def _conformance(ws, strict=False):
    saved = sys.argv
    out, err = io.StringIO(), io.StringIO()
    try:
        sys.argv = ["conformance_check.py", "--workspace", str(ws)] + (
            ["--strict"] if strict else [])
        with redirect_stdout(out), redirect_stderr(err):
            code = cc.main()
    finally:
        sys.argv = saved
    return code, out.getvalue()


def _read_all(ws):
    return {p.relative_to(ws).as_posix(): p.read_text(encoding="utf-8")
            for p in mw._text_files(ws)}


def _finding_count(out):
    """(blockers, warnings) parsed from a conformance summary line."""
    m = re.search(r"(\d+) blocker\(s\), (\d+) warning\(s\)", out)
    return (int(m.group(1)), int(m.group(2))) if m else None


def _split_records(ws, mapping):
    """Partition a _read_all() mapping into (non_records, records) by the
    migrator's OWN predicate — so the tests cannot drift from the tool's
    definition of the append-only record set."""
    non_records, records = {}, {}
    for rel, text in mapping.items():
        target = records if mw._is_append_only_record(ws, ws / rel) else non_records
        target[rel] = text
    return non_records, records


class MigrateMechanicsTest(unittest.TestCase):
    def test_flips_version_and_all_stamps(self):
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            self.assertEqual(_stamp(ws, ["--profile", "3agent.local"]), 0)
            _downgrade(ws)
            # sanity: the fixture really is a v2.6 workspace now
            self.assertIn("| PROTOCOL_VERSION | v2.6 |",
                          (ws / "BINDINGS.md").read_text(encoding="utf-8"))
            before = _read_all(ws)
            res = mw.migrate(ws)
            self.assertEqual(res["status"], "migrated")
            self.assertIn("| PROTOCOL_VERSION | v2.7 |",
                          (ws / "BINDINGS.md").read_text(encoding="utf-8"))
            non_records, records = _split_records(ws, _read_all(ws))
            # no old stamp survives on any NON-record file
            for rel, text in non_records.items():
                self.assertNotIn("[PROTOCOL v2.6]", text, msg=rel)
            # the complementary half: append-only records KEEP the stamp of the
            # version they were created under — a record's banner is part of
            # the record, so it is never rewritten.
            self.assertTrue(records, "fixture has no append-only records")
            _, records_before = _split_records(ws, before)
            for rel, text in records.items():
                if "[PROTOCOL v2.6]" in records_before[rel]:
                    self.assertIn("[PROTOCOL v2.6]", text, msg=rel)

    def test_migrated_matches_fresh_stamp_except_untouched_records(self):
        """The v2.6 migrator guaranteed migrated == freshly-stamped byte for
        byte. v2.7 deliberately drops that: append-only records are not
        rewritten, so they keep their creation stamp while a fresh stamp emits
        the new one. The replacement invariant is stronger where it still
        holds — non-records match a fresh stamp exactly, and records are
        byte-identical to their PRE-migration state (untouched, not merely
        old-stamped) — and the migrator reports every record it kept."""
        with tempfile.TemporaryDirectory() as d:
            downgraded = Path(d) / "down"
            fresh = Path(d) / "fresh"
            _stamp(downgraded, ["--profile", "3agent.local"])
            _stamp(fresh, ["--profile", "3agent.local"])
            _downgrade(downgraded)
            # A record carrying NO old-version token at all. The ruling requires
            # records_kept to be exhaustive "including zero-token/empty ones",
            # and without such a file in the fixture that clause is untested:
            # replay proved a migrator filtering `if txt.count(STAMP_FROM)`
            # left this test green, because every other record bears a token.
            (downgraded / "channel" / "zero_token_record.md").write_text(
                "a channel record with no protocol stamp at all\n",
                encoding="utf-8")
            before = _read_all(downgraded)
            res = mw.migrate(downgraded)
            self.assertEqual(res["status"], "migrated")

            after = _read_all(downgraded)
            non_records, records = _split_records(downgraded, after)
            fresh_non_records, _ = _split_records(fresh, _read_all(fresh))
            # (i) everything that is NOT an append-only record still matches a
            #     fresh stamp exactly
            self.assertEqual(non_records, fresh_non_records)
            # (ii) records are untouched ENTIRELY — byte-identical to their
            #      pre-migration state, not just "an old stamp survived"
            _, records_before = _split_records(downgraded, before)
            self.assertEqual(records, records_before)
            # (iii) every kept record is REPORTED, exhaustively — including any
            #       carrying zero old-version tokens, so the skip is auditable
            #       rather than silent
            reported = {Path(p).resolve() for p, _ in res["records_kept"]}
            expected = {(downgraded / rel).resolve() for rel in records}
            self.assertEqual(reported, expected)

    def test_migrated_workspace_gates_strict_clean(self):
        """The closing property that makes the dropped byte-identical
        invariant safe: keeping records must cost NOTHING in conformance
        terms. Pin-aware `_record_stamp_ok` accepting a creation-stamped
        record under a newer pin is the other half of the design — without
        it, keeping records would just be drift.

        Measured against a FRESH stamp rather than against literal
        strict-clean: an unbound fixture always carries `{{FILL}}` slot
        warnings, so "--strict exits 0" is unreachable here and asserting it
        tests the fixture, not the design. The real property is that a
        migrated workspace is no less conformant than a freshly stamped one,
        and that no kept record produces a stamp finding."""
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            fresh = Path(d) / "fresh"
            _stamp(ws, ["--profile", "3agent.local"])
            _stamp(fresh, ["--profile", "3agent.local"])
            _downgrade(ws)
            res = mw.migrate(ws)
            self.assertEqual(res["status"], "migrated")
            self.assertTrue(res["records_kept"], "no records were kept")

            code, out = _conformance(ws, strict=True)
            fresh_code, fresh_out = _conformance(fresh, strict=True)
            self.assertIn("0 blocker", out)
            # no kept record is reported as a banner-stamp finding — the
            # wording `_record_stamp_ok` emits when it rejects one. (Replay:
            # mutating it to demand stamp == pin must turn this red.)
            self.assertNotIn("banner lacks", out)
            # and migration introduced no findings a fresh stamp lacks
            self.assertEqual(_finding_count(out), _finding_count(fresh_out),
                             msg=f"migrated:\n{out}\nfresh:\n{fresh_out}")
            self.assertEqual(code, fresh_code)

    def test_idempotent_on_already_v26(self):
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "2agent.local"])
            before = _read_all(ws)
            res = mw.migrate(ws)
            self.assertEqual(res["status"], "already")
            self.assertEqual(_read_all(ws), before)  # untouched

    def test_refuses_unknown_version(self):
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "2agent.local"])
            _downgrade(ws)
            _set_slot(ws, "PROTOCOL_VERSION", "v2.9")
            before = _read_all(ws)
            code, out = _migrate_main(ws)
            self.assertEqual(code, 1)
            self.assertIn("v2.9", out)
            self.assertEqual(_read_all(ws), before)  # nothing written

    def test_dry_run_writes_nothing(self):
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "2agent.local"])
            _downgrade(ws)
            before = _read_all(ws)
            code, out = _migrate_main(ws, ["--dry-run"])
            self.assertEqual(code, 0)
            self.assertIn("DRY RUN", out)
            self.assertEqual(_read_all(ws), before)  # unchanged


class MigrateStructuralPverTest(unittest.TestCase):
    """The MAJOR: a whitespace-valid PROTOCOL_VERSION row must fully migrate —
    detection (whitespace-tolerant) and the rewrite must agree, never leaving a
    half-migrated workspace whose stamps flipped but whose pin stayed v2.6."""

    def test_whitespace_valid_pver_fully_migrates(self):
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "2agent.local"])
            _downgrade(ws)
            # rewrite the row with non-canonical inner spacing, straight to disk
            b = ws / "BINDINGS.md"
            lines = b.read_text(encoding="utf-8").splitlines(keepends=True)
            for i, line in enumerate(lines):
                if line.lstrip().startswith("| PROTOCOL_VERSION |"):
                    lines[i] = "|  PROTOCOL_VERSION  |   v2.6   |\n"
                    break
            b.write_text("".join(lines), encoding="utf-8")
            self.assertEqual(cc.pinned_version(cc.parse_bindings(ws)), "v2.6")

            res = mw.migrate(ws)
            self.assertEqual(res["status"], "migrated")
            # the pin is now genuinely v2.7 (not a half-migration)
            self.assertEqual(cc.pinned_version(cc.parse_bindings(ws)), "v2.7")
            row = _pver_row(ws)
            self.assertIn("v2.7", row)
            self.assertNotIn("v2.6", row)

    def test_extra_cell_pver_row_migrates_without_dropping_content(self):
        # round-2 MAJOR: a PROTOCOL_VERSION row with a stray extra cell is
        # detected as v2.6 and must migrate WITHOUT silently dropping that cell.
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "2agent.local"])
            _downgrade(ws)
            b = ws / "BINDINGS.md"
            lines = b.read_text(encoding="utf-8").splitlines(keepends=True)
            for i, line in enumerate(lines):
                if line.lstrip().startswith("| PROTOCOL_VERSION |"):
                    lines[i] = "| PROTOCOL_VERSION | v2.6 | (pinned 2026-01-01) |\n"
                    break
            b.write_text("".join(lines), encoding="utf-8")
            self.assertEqual(cc.pinned_version(cc.parse_bindings(ws)), "v2.6")

            res = mw.migrate(ws)
            self.assertEqual(res["status"], "migrated")
            self.assertEqual(cc.pinned_version(cc.parse_bindings(ws)), "v2.7")
            row = _pver_row(ws)
            self.assertIn("(pinned 2026-01-01)", row)   # extra cell NOT dropped
            self.assertNotIn("v2.6", row)

    def test_pver_row_migrated_matching_and_preservation(self):
        # non-matching rows -> None; a matching row flips ONLY the version cell,
        # preserving inner spacing AND any extra trailing cells.
        hop = ("v2.6", "v2.7")
        self.assertIsNone(mw._pver_row_migrated("| OTHER | v2.6 |", *hop))
        self.assertIsNone(
            mw._pver_row_migrated("| PROTOCOL_VERSION | v2.7 |", *hop))
        self.assertEqual(
            mw._pver_row_migrated("|  PROTOCOL_VERSION | v2.6  |", *hop),
            "|  PROTOCOL_VERSION | v2.7  |")
        self.assertEqual(
            mw._pver_row_migrated("| PROTOCOL_VERSION | v2.6 | (pinned x) |", *hop),
            "| PROTOCOL_VERSION | v2.7 | (pinned x) |")
        # the helper is hop-agnostic: the SAME code drives the older leg, so
        # the v2.5 hop cannot rot behind a v2.6-only implementation
        older = ("v2.5", "v2.6")
        self.assertEqual(
            mw._pver_row_migrated("| PROTOCOL_VERSION | v2.5 |", *older),
            "| PROTOCOL_VERSION | v2.6 |")
        self.assertIsNone(
            mw._pver_row_migrated("| PROTOCOL_VERSION | v2.6 |", *older))


class MigratePreservesProtectedContentTest(unittest.TestCase):
    """The BLOCKER: the literal `[PROTOCOL v2.6]` token appearing OFF a
    stamp-bearing line (in an authority row, or in prose) must never be flipped.
    These fixtures are hand-built so they don't ride the migrator's own logic."""

    def test_proxy_auth_row_with_stamp_token_is_untouched(self):
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "3agent.local"])
            _downgrade(ws)
            # an authority row that happens to mention the bracketed token
            _set_slot(ws, "PROXY_AUTH",
                      "off — authority note mentioning [PROTOCOL v2.6] stays first-hand")
            b = ws / "BINDINGS.md"
            before_row = next(l for l in b.read_text(encoding="utf-8").splitlines()
                              if l.lstrip().startswith("| PROXY_AUTH |"))

            mw.migrate(ws)

            after = b.read_text(encoding="utf-8")
            after_row = next(l for l in after.splitlines()
                             if l.lstrip().startswith("| PROXY_AUTH |"))
            self.assertEqual(after_row, before_row)          # row byte-identical
            self.assertIn("[PROTOCOL v2.6]", after_row)       # token NOT flipped
            # meanwhile the header + the pver row DID migrate
            self.assertIn("[PROTOCOL v2.7]", after.splitlines()[0])
            self.assertIn("| PROTOCOL_VERSION | v2.7 |", after)

    def test_memory_body_stamp_token_is_untouched(self):
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "2agent.local"])
            _downgrade(ws)
            m = ws / "memory" / "owner" / "MEMORY.md"
            note = "\nhistorical note: [PROTOCOL v2.6] was discussed here, not a stamp.\n"
            m.write_text(m.read_text(encoding="utf-8") + note, encoding="utf-8")

            mw.migrate(ws)

            self.assertIn("[PROTOCOL v2.6] was discussed",
                          m.read_text(encoding="utf-8"))

    def test_left_untouched_tokens_are_reported(self):
        # a token on a non-stamp (prose) line is skipped AND surfaced, so the
        # conservative skip is auditable — not silent.
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "2agent.local"])
            _downgrade(ws)
            (ws / "NOTES.md").write_text(
                "**From:** a past session [PROTOCOL v2.6] provenance line\n",
                encoding="utf-8")
            res = mw.migrate(ws)
            left = {p.name: n for p, n in res["left_untouched"]}
            self.assertEqual(left.get("NOTES.md"), 1)
            # the token really was left in place
            self.assertIn("[PROTOCOL v2.6]",
                          (ws / "NOTES.md").read_text(encoding="utf-8"))

    def test_left_untouched_surfaced_on_cli(self):
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "2agent.local"])
            _downgrade(ws)
            (ws / "NOTES.md").write_text(
                "prose mentioning [PROTOCOL v2.6] not a stamp\n", encoding="utf-8")
            code, out = _migrate_main(ws, ["--dry-run"])  # dry-run still reports
            self.assertEqual(code, 0)
            self.assertIn("left untouched", out)
            self.assertIn("NOTES.md", out)

    def test_memory_body_heading_with_token_is_untouched(self):
        # round-2 (Codex): a token on a memory-body HEADING (not the file's
        # banner) is real content — it must NOT be flipped just because the line
        # starts with `#`.
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "2agent.local"])
            _downgrade(ws)
            m = ws / "memory" / "owner" / "MEMORY.md"
            body = ("\n## Historical note: [PROTOCOL v2.6] was discussed here, "
                    "not a stamp.\n")
            m.write_text(m.read_text(encoding="utf-8") + body, encoding="utf-8")

            res = mw.migrate(ws)

            self.assertIn("## Historical note: [PROTOCOL v2.6]",
                          m.read_text(encoding="utf-8"))
            left = {p.name: n for p, n in res["left_untouched"]}
            self.assertEqual(left.get("MEMORY.md"), 1)  # surfaced, not flipped

    def test_fenced_example_stamp_is_not_flipped(self):
        # round-2 (peer): an EXAMPLE stamp heading inside a fenced code block is
        # not the file's banner, so it is left intact.
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "2agent.local"])
            _downgrade(ws)
            doc = ws / "EXAMPLE.md"
            content = ("# Real banner heading\n\n"
                       "A fresh stamp heading looks like:\n\n"
                       "```\n"
                       "# BINDINGS — sample [PROTOCOL v2.6]\n"
                       "```\n"
                       "Do not copy literally.\n")
            doc.write_text(content, encoding="utf-8")

            mw.migrate(ws)

            self.assertIn("# BINDINGS — sample [PROTOCOL v2.6]",
                          doc.read_text(encoding="utf-8"))

    def test_prose_banner_with_token_is_untouched(self):
        # the banner line itself, if it is prose (not a heading/docstring), is
        # not a stamp — its token is left alone.
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "2agent.local"])
            _downgrade(ws)
            doc = ws / "PROSE.md"
            content = "We migrated from [PROTOCOL v2.6] last week.\n"
            doc.write_text(content, encoding="utf-8")

            mw.migrate(ws)

            self.assertEqual(doc.read_text(encoding="utf-8"), content)

    def test_stamp_on_banner_after_shebang_flips(self):
        # the banner is the SECOND content line when the first is a shebang —
        # that stamp must still flip (e.g. a stamped .sh / .py tool).
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "2agent.local"])
            _downgrade(ws)
            sh = ws / "tool.sh"
            sh.write_text("#!/bin/bash\n# helper [PROTOCOL v2.6] banner\necho hi\n",
                          encoding="utf-8")

            mw.migrate(ws)

            out = sh.read_text(encoding="utf-8")
            self.assertIn("# helper [PROTOCOL v2.7] banner", out)
            self.assertNotIn("[PROTOCOL v2.6]", out)

    def test_bom_prefixed_banner_stamp_flips_and_bom_survives(self):
        # a real live channel file began with a UTF-8 BOM before its `# ...`
        # banner (Windows-editor artifact, found 2026-07-09): str.lstrip() does not
        # strip U+FEFF, so the banner was misclassified as prose and skipped.
        # The stamp must flip AND the BOM must be preserved byte-for-byte.
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "2agent.local"])
            _downgrade(ws)
            doc = ws / "BOMMED.md"
            content = "﻿# channel file 2026-07-06b [PROTOCOL v2.6]\nbody\n"
            doc.write_text(content, encoding="utf-8")

            mw.migrate(ws)

            out = doc.read_text(encoding="utf-8")
            self.assertTrue(out.startswith("﻿# channel file"))
            self.assertIn("[PROTOCOL v2.7]", out)
            self.assertNotIn("[PROTOCOL v2.6]", out)

    def test_mixed_stamp_on_the_banner_is_not_corrupted(self):
        # even on the banner line, the exact token requires the closing bracket,
        # so `[PROTOCOL v2.6 / v2.7]` is left intact.
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "2agent.local"])
            _downgrade(ws)
            mixed = ws / "MIXED.md"
            content = "# note [PROTOCOL v2.6 / v2.7] mixed stamp\n"
            mixed.write_text(content, encoding="utf-8")

            mw.migrate(ws)

            self.assertEqual(mixed.read_text(encoding="utf-8"), content)


class MigratePreservesBytesTest(unittest.TestCase):
    """Line endings and undecodable files."""

    def test_line_endings_preserved(self):
        for eol in (b"\r\n", b"\n"):
            with tempfile.TemporaryDirectory() as d:
                ws = Path(d) / "ws"
                _stamp(ws, ["--profile", "2agent.local"])
                _downgrade(ws)
                b = ws / "BINDINGS.md"
                lf = b.read_bytes().replace(b"\r\n", b"\n")   # normalize to LF
                b.write_bytes(lf.replace(b"\n", eol))          # force target EOL

                mw.migrate(ws)

                out = b.read_bytes()
                self.assertIn(eol, out)                        # forced EOL survived
                if eol == b"\n":
                    self.assertNotIn(b"\r\n", out)             # no LF->CRLF rewrite
                # and the stamp actually flipped
                self.assertIn(b"[PROTOCOL v2.7]", out)
                self.assertNotIn(b"[PROTOCOL v2.6]", out)

    def test_undecodable_file_is_skipped(self):
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "2agent.local"])
            _downgrade(ws)
            junk = ws / "BINARY.md"           # text-like extension, invalid utf-8
            raw = b"\xff\xfe\x00 not utf-8 [PROTOCOL v2.6]\x00"
            junk.write_bytes(raw)

            res = mw.migrate(ws)              # must not raise

            self.assertEqual(res["status"], "migrated")
            self.assertEqual(junk.read_bytes(), raw)   # byte-identical, untouched


class MigratePreservesAuthorityTest(unittest.TestCase):
    NONCANON_PA = ("on for enumerated classes; EXCLUDED first-hand: "
                   "everything on the EMBARGOES row, merges, PROXY_AUTH itself")

    def _v25_ws_with_noncanon_proxy(self, d):
        ws = Path(d) / "ws"
        _stamp(ws, ["--profile", "3agent.local"])
        _downgrade(ws)
        _set_slot(ws, "PROXY_AUTH", self.NONCANON_PA)
        return ws

    def test_migrate_never_edits_proxy_auth_slot(self):
        with tempfile.TemporaryDirectory() as d:
            ws = self._v25_ws_with_noncanon_proxy(d)
            mw.migrate(ws)
            slots = cc.parse_bindings(ws)
            # the PROXY_AUTH value is byte-for-byte what we set — untouched
            self.assertEqual(slots["PROXY_AUTH"], self.NONCANON_PA)

    def test_prints_proxy_auth_reword_reminder(self):
        with tempfile.TemporaryDirectory() as d:
            ws = self._v25_ws_with_noncanon_proxy(d)
            _, out = _migrate_main(ws)
            self.assertIn("PROXY_AUTH", out)
            self.assertIn("FIRST-HAND ONLY", out)
            # names at least one missing canonical super-class verbatim
            self.assertIn("outward-facing/publish actions", out)

    def test_canonical_proxy_auth_gives_no_gaps(self):
        # A fresh v2.7 stamp's PROXY_AUTH is canonical → no gaps reported.
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "3agent.local"])
            self.assertEqual(mw.proxy_auth_gaps(cc.parse_bindings(ws)), [])


class MigrateSlotAdviceTest(unittest.TestCase):
    def test_prints_new_v26_slot_advice(self):
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "3agent.local"])
            _downgrade(ws)
            # a real v2.6 workspace lacks the AUTONOMY row; remove it so the
            # advice fires (AUTONOMY always applies → printed under "add")
            b = ws / "BINDINGS.md"
            b.write_text("\n".join(
                l for l in b.read_text(encoding="utf-8").splitlines()
                if not l.lstrip().startswith("| AUTONOMY |")) + "\n",
                encoding="utf-8")
            _, out = _migrate_main(ws)
            self.assertIn("AUTONOMY", out)

    def test_git_sync_only_slots_flagged_not_applicable_for_local(self):
        # WORKSPACE_REMOTE / SECRETS are git-sync-only; on a local-fs workspace
        # they must be reported as not applicable, honouring "which apply".
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "2agent.local"])
            _downgrade(ws)
            _, out = _migrate_main(ws)
            self.assertIn("not applicable to this local-fs workspace", out)
            self.assertIn("WORKSPACE_REMOTE", out)


class MigrateGitSyncProfileTest(unittest.TestCase):
    def test_git_sync_profile_round_trips(self):
        with tempfile.TemporaryDirectory() as d:
            downgraded = Path(d) / "down"
            fresh = Path(d) / "fresh"
            if _stamp(downgraded, ["--profile", "3agent.git-sync"]) != 0:
                self.skipTest("3agent.git-sync profile not available")
            _stamp(fresh, ["--profile", "3agent.git-sync"])
            _downgrade(downgraded)
            before = _read_all(downgraded)
            res = mw.migrate(downgraded)
            self.assertEqual(res["status"], "migrated")
            # same replacement invariant as the local profile: non-records match
            # a fresh stamp, records are untouched entirely.
            non_records, records = _split_records(downgraded, _read_all(downgraded))
            fresh_non_records, _ = _split_records(fresh, _read_all(fresh))
            self.assertEqual(non_records, fresh_non_records)
            _, records_before = _split_records(downgraded, before)
            self.assertEqual(records, records_before)


class MigrateChainedHopsTest(unittest.TestCase):
    """The v2.5 -> v2.7 ladder: BOTH hops in ONE run of ONE checkout. The v2.5
    hop is not a legacy leftover — it is a supported public capability, and
    removing it silently was the defect this release exists to correct."""

    def test_hop_chain_decision_tree(self):
        # the tree the docs promise, asserted against the code that derives it
        self.assertEqual(mw._hop_chain("v2.5"),
                         [("v2.5", "v2.6"), ("v2.6", "v2.7")])
        self.assertEqual(mw._hop_chain("v2.6"), [("v2.6", "v2.7")])
        self.assertEqual(mw._hop_chain("v2.7"), [])       # no-op
        self.assertIsNone(mw._hop_chain("v2.4"))          # too old
        self.assertIsNone(mw._hop_chain("v9.9"))          # unknown
        self.assertIsNone(mw._hop_chain(None))            # absent

    def test_v25_workspace_runs_both_hops_in_one_run(self):
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "3agent.local"])
            _downgrade(ws, to="v2.5")
            self.assertIn("| PROTOCOL_VERSION | v2.5 |",
                          (ws / "BINDINGS.md").read_text(encoding="utf-8"))
            res = mw.migrate(ws)
            self.assertEqual(res["status"], "migrated")
            self.assertEqual(res["version_from"], "v2.5")   # ORIGINAL pin
            self.assertEqual(res["version_to"], "v2.7")
            self.assertEqual(res["hops"], [("v2.5", "v2.6"), ("v2.6", "v2.7")])
            self.assertIn("| PROTOCOL_VERSION | v2.7 |",
                          (ws / "BINDINGS.md").read_text(encoding="utf-8"))
            # no INTERMEDIATE version is left stranded on a non-record file
            non_records, _ = _split_records(ws, _read_all(ws))
            for rel, text in non_records.items():
                self.assertNotIn("[PROTOCOL v2.5]", text, msg=rel)
                self.assertNotIn("[PROTOCOL v2.6]", text, msg=rel)

    def test_v25_records_kept_byte_identical_across_BOTH_hops(self):
        """The keep-records doctrine is current doctrine at EVERY hop — the old
        rewrite-records behaviour must not come back on the v2.5 leg."""
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "3agent.local"])
            _downgrade(ws, to="v2.5")
            (ws / "channel" / "zero_token_record.md").write_text(
                "a v2.5-era channel record with no protocol stamp at all\n",
                encoding="utf-8")
            before = _read_all(ws)
            res = mw.migrate(ws)
            self.assertEqual(res["status"], "migrated")

            _, records_after = _split_records(ws, _read_all(ws))
            _, records_before = _split_records(ws, before)
            # untouched ENTIRELY across the whole chain
            self.assertEqual(records_after, records_before)
            # and still carrying their v2.5 creation stamp under a v2.7 pin
            self.assertTrue(
                any("[PROTOCOL v2.5]" in t for t in records_after.values()),
                "fixture proves nothing: no record kept a v2.5 stamp")
            # exhaustive reporting across the chain, zero-token file included
            reported = {Path(p).resolve() for p, _ in res["records_kept"]}
            expected = {(ws / rel).resolve() for rel in records_after}
            self.assertEqual(reported, expected)

    def test_v25_era_records_stay_green_under_v27_pin(self):
        """OC-142 pin 1 — the load-bearing property of the whole design. A
        chained v2.5 -> v2.7 migration leaves `[PROTOCOL v2.5]`-stamped records
        in a v2.7-pinned workspace, and that must be GREEN: pin-aware
        `_record_stamp_ok` accepts any supported stamp at-or-below the pin.
        If this ever stopped holding, chained migration would silently
        manufacture findings on records it never touched.

        Measured as conformance PARITY against a fresh stamp — the
        fixture-independent encoding, since an unbound workspace always carries
        {{FILL}} warnings of its own."""
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            fresh = Path(d) / "fresh"
            _stamp(ws, ["--profile", "3agent.local"])
            _stamp(fresh, ["--profile", "3agent.local"])
            _downgrade(ws, to="v2.5")
            res = mw.migrate(ws)
            self.assertEqual(res["status"], "migrated")

            # the premise: v2.5 stamps really did survive into a v2.7 workspace
            _, records = _split_records(ws, _read_all(ws))
            self.assertTrue(
                any("[PROTOCOL v2.5]" in t for t in records.values()),
                "premise failed: no v2.5-stamped record survived the chain")
            self.assertIn("| PROTOCOL_VERSION | v2.7 |",
                          (ws / "BINDINGS.md").read_text(encoding="utf-8"))

            code, out = _conformance(ws, strict=True)
            fresh_code, fresh_out = _conformance(fresh, strict=True)
            self.assertIn("0 blocker", out)
            self.assertNotIn("banner lacks", out)
            self.assertEqual(_finding_count(out), _finding_count(fresh_out),
                             msg=f"chained:\n{out}\nfresh:\n{fresh_out}")
            self.assertEqual(code, fresh_code)

    def test_chained_dry_run_previews_the_whole_ladder(self):
        """A dry run of a v2.5 workspace must preview BOTH legs, not just the
        first — the later legs read the earlier leg's would-be output."""
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "3agent.local"])
            _downgrade(ws, to="v2.5")
            before = _read_all(ws)
            res = mw.migrate(ws, dry_run=True)
            self.assertEqual(res["status"], "dry-run")
            self.assertEqual(res["hops"], [("v2.5", "v2.6"), ("v2.6", "v2.7")])
            # BINDINGS is planned on BOTH legs, so it appears once per hop
            bindings_passes = [t for t in res["changed"]
                               if t[0].name == "BINDINGS.md"]
            self.assertEqual(len(bindings_passes), 2, msg=str(res["changed"]))
            self.assertEqual(_read_all(ws), before)  # nothing written

    def test_unsupported_message_names_the_supported_pins(self):
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "2agent.local"])
            _set_slot(ws, "PROTOCOL_VERSION", "v2.4")
            code, out = _migrate_main(ws)
            self.assertEqual(code, 1)
            # the refusal must teach the supported starting pins
            for ver in mw.SUPPORTED_FROM:
                self.assertIn(ver, out)


class MigrateConformanceTest(unittest.TestCase):
    def test_conformance_passes_after_migrate(self):
        # A canonical v2.6 workspace (a downgraded fresh stamp) is fully
        # conformant under v2.7 once migrated — 0 blockers.
        with tempfile.TemporaryDirectory() as d:
            ws = Path(d) / "ws"
            _stamp(ws, ["--profile", "3agent.local"])
            _downgrade(ws)
            mw.migrate(ws)
            code, out = _conformance(ws)
            self.assertEqual(code, 0)  # warnings only (unfilled FILL slots)
            self.assertIn("0 blocker", out)


if __name__ == "__main__":
    unittest.main()
